### ISSUE TITLE
precision issue

### ISSUE THREAD

**Issue by leimingyu** [mbeyeler/opencv-machine-learning#2]
In notebooks/03.01-Measuring-Model-Performance-with-Scoring-Functions.ipynb,
cell 15

`precision = np.sum(true_positive) / np.sum(true_positive + true_negative)`

which should be 

`precision = np.sum(true_positive) / np.sum(true_positive + false_positive)`

**Comment by mbeyeler** [comment]
Good catch, thanks!

**Comment by mbeyeler** [comment]
Close #2 via 74fc3978f41b01c180104a58f733e9b3e093afdd.
