### ISSUE TITLE
Binder problems

### ISSUE THREAD

**Issue by goobering** [mbeyeler/opencv-machine-learning#3]
Unfortunately your Binder link seems to be misbehaving. 

[Binder link provided on homepage](https://mybinder.org/v2/gh/mbeyeler/opencv-machine-learning/master)

```
UnsatisfiableError: The following specifications were found to be in conflict:
 - opencv=3.1
 - pandas==0.18.0=np110py27_0
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by mbeyeler** [comment]
Thanks for the heads-up. For some reason it's trying to install pandas for Python 2.7. I'll have a look at it.

**Comment by mbeyeler** [comment]
Should work again. The up-to-date Binder link is: https://mybinder.org/v2/gh/mbeyeler/opencv-machine-learning/master.
