### ISSUE TITLE
HTML:Bankfraud-LV detected by Avast AV; download/connection aborted

### ISSUE THREAD

**Issue by gdwhite** [mbeyeler/opencv-machine-learning#7]
Avast AV detects HTML:Bankfraud-LV & aborts download/connection. Here's the relevant line from the Avast log file:

10/29/2018 10:20:07 PM	https://codeload.github.com/mbeyeler/opencv-machine-learning/zip/master|>opencv-machine-learning-master\notebooks\data\chapter7\BG.tar.gz|>BG.tar|>BG\2004\09\1095786133.25239_75.txt|>PartNo_0#2719639900 [L] HTML:Bankfraud-LV [Trj] (0)

![html bankfraud-lv - avast detection](https://user-images.githubusercontent.com/2054830/47692433-f9c3c180-dbcb-11e8-8127-ef2a9ec3f413.png)

**Comment by mbeyeler** [comment]
Lol what the... Is this for real? Let me have a look...

**Comment by mbeyeler** [comment]
Alright, so this is from the chapter on [classifying spam emails](https://github.com/mbeyeler/opencv-machine-learning/blob/2513edab423a4f067ebcc4c867203db1064c35c7/notebooks/07.02-Classifying-Emails-Using-Naive-Bayes.ipynb), which uses the publicly available [Enron-Spam dataset](http://nlp.cs.aueb.gr/software_and_datasets/Enron-Spam/index.html) from Athens University. This dataset contains a number of innocuous emails (classified as 'ham') and just a bunch of spam.

The file in question is an example of a spam email (from the 'BG' folder) pretending to be from CitiBank. So in a sense, Avast is right that this is a phishing email trying to commit bank fraud 😄 but as a text file it certainly does not contain a Trojan. 

I know that's easy to say, so maybe if you don't trust it, the easiest way out is not to download the data for Chapter 7. You could download the data directly from the original source if you trust them (Natural Language Processing Group at Athens: [nlp.cs.aueb.gr](http://nlp.cs.aueb.gr/software_and_datasets/Enron-Spam/index.html)) or you could use any other email dataset instead (e.g., they have another popular one that's called the [Ling-Spam corpus](http://www.aueb.gr/users/ion/data/lingspam_public.tar.gz), and they have lots more cool stuff [here](http://nlp.cs.aueb.gr/software.html)).

The content of the text file in question is printed below.

Cheers,
Michael


```
Return-Path: <Citibank.message@emailmessage.citibank.com>
Delivered-To: em-ca-bait@em.ca
Received: (qmail 16009 invoked by uid 115); 21 Sep 2004 15:57:50 -0000
Received: from Citibank.message@emailmessage.citibank.com by churchill by uid 64011 with qmail-scanner-1.22 
 (clamdscan: 0.75-1. spamassassin: 2.63.  Clear:RC:0(66.33.237.222):. 
 Processed in 0.44637 secs); 21 Sep 2004 15:57:50 -0000
Received: from hrbg-66-33-237-222-nonpppoe.dsl.hrbg.epix.net (66.33.237.222)
  by churchill.factcomp.com with SMTP; 21 Sep 2004 15:57:50 -0000
X-Message-Info: 9hGWsd261aRE/mzVydeHYhYPycntP8Kd
Received: from sprightly ([120.186.99.115])
          by cou76-mail.moyer.adsorb.destitute.cable.rogers.com
          (InterMail vM.5.01.05.12 159-633-015-445-824-04571071) with ESMTP
          id <06947712332831.ELVX736880.ngb15-mail.sodium.grapefruit.net.cable.rogers.com@mutilate>
          for <asetar@em.ca>; Tue, 21 Sep 2004 10:51:47 -0600
Message-ID: <333460z0xomp$1316d6m0$3641a4c0@phylogeny>
Reply-To: "Lucia Foster" <Citibank.message@emailmessage.citibank.com>
From: "Lucia Foster" <Citibank.message@emailmessage.citibank.com>
To: <asetar@em.ca>
Subject: ATTN: Security Update from Citibank MsgID# 92379245
Date: Tue, 21 Sep 2004 21:51:47 +0500
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="--419776125423611"

----419776125423611
Content-Type: text/html;
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<title>Untitled Document</title>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859=
-1">
</head>

<body bgcolor=3D"#FFFFFF" text=3D"#000000">
CITIBANK(R) 
<p>Dear Citibank Customer:</p>
<p>Recently there have been a large number computer terrorist attacks over=
 our 
  database server. In order to safeguard your account, we require that you=
 update 
  your Citibank ATM/Debit card PIN. </p>
<p>This update is requested of you as a precautionary measure against frau=
d. Please 
  note that we have no particular indications that your details have been =
compromised 
  in any way.</p>
<p>This process is mandatory, and if not completed within the nearest time=
 your 
  account may be subject to temporary suspension.</p>
<p>Please make sure you have your Citibank ATM/Debit card and your login d=
etails 
  at hand.</p>
<p>To securely update your Citibank ATM/Debit card PIN please go to:</p>
<p><a href=3D"http://219.138.133.5/customer/">Customer Verification 
  Form</a></p>
<p>Please note that this update applies to your Citibank ATM/Debit card - =
which 
  is linked directly to your checking account, not Citibank credit cards.<=
/p>
<p>Thank you for your prompt attention to this matter and thank you for us=
ing 
  Citibank!</p>
<p>Regards,</p>
<p>Customer Support MsgID# 92379245</p>
<p>(C)2004 Citibank. Citibank, N.A., Citibank, F.S.B., <br>
  Citibank (West), FSB. Member FDIC.Citibank and Arc <br>
  Design is a registered service mark of Citicorp.</p>
</body>
</html>

----419776125423611--
```
