### ISSUE TITLE
Real-time two-way synchronization between .tex and .ipynb files in the format of ultimate publication. 

### ISSUE THREAD

**Issue by hongyi-zhao** [mbeyeler/opencv-machine-learning#8]
Hi,

I noted that the project is in the same format as the ultimate publicized book. So I want to achieve the following aims based on the project to generate the corresponding .tex source codes for publication with the following requirements:

1. The .tex files for this project can be edited and managed by LaTeX IDE, say, [texstudio](https://github.com/texstudio-org/texstudio).
2. The .tex files are generated by .ipynb files of this project.
3. Each time when I edited the .tex files or the corresponding .ipynb notebooks, synchronization will be triggered between them to ensure the changes are applied to both appropriately. 
 
Is it possible for me to  achieve this goal for this project?

Any hints will be highly appreciated.

Best regards
HY

**Comment by mbeyeler** [comment]
I am not sure I understand. There *are* slight differences between the Jupyter Notebooks you see here and the book you can buy from Packt - the notebooks are shorter while the book often has more explanations and more examples. They also have their own formatting team, so it's not straight ipynb->tex.

I don't think there's any way to generate a Jupyter Notebook from a .tex file. But, you can convert .ipynb to .tex! You could use [nbconvert](https://nbconvert.readthedocs.io/en/latest) that is triggered with a [webhook](https://developer.github.com/webhooks/) every time a new commit is pushed. You could automate the process with [GitHub Actions](https://github.com/features/actions), so a new PDF is rendered on every new commit. Hope this helps.
