### ISSUE TITLE
A dataset is missing

### ISSUE THREAD

**Issue by sshojiro** [mbeyeler/opencv-machine-learning#9]
Hello,

I am new to computer vision and learning HOG x SVM classifier introduced in 6.2 or so of your book. However, I found that the following link is out-of-service:
http://cbcl.mit.edu/projects/cbcl/software-datasets/pedestrians128x64.tar.gz

Could you provide an alternative link or datasets? Thank you.

**Comment by mbeyeler** [comment]
It looks like it moved here: http://cbcl.mit.edu/software-datasets/PedestrianData.html

**Comment by sshojiro** [comment]
@mbeyeler Thank you for your quick response. But unfortunately, the link you pasted has only the information, not the link to image files. The download button in the html page is linked to the exactly same link I pasted above. I'd appreciate it if you tell me whether the dataset has been deleted. Thank you for your support.

**Comment by mbeyeler** [comment]
I see, in that case: I don't know, it's not my dataset... Maybe you could email the Poggio lab at MIT and ask? It looks like they recently updated their website. It might be an easy fix for them if they still have the data. Thanks
